# 1. Build frontend
FROM node:16 AS frontend

WORKDIR /app

COPY app/package*.json ./
RUN npm ci

COPY app/ ./
# Add build-time env vars for React
ARG REACT_APP_MAPBOX_TOKEN
ARG REACT_APP_MAPBOX_DATASETS_TOKEN
ARG REACT_APP_GOOGLE_MAP_API_KEY
ARG REACT_APP_GOOGLE_GEOCODE_API_KEY
ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH
ARG REACT_APP_FIREBASE_PROJECT
ARG REACT_APP_FIREBASE_BUCKET
ARG REACT_APP_FIREBASE_MESS
ARG REACT_APP_FIREBASE_APP_ID
ARG REACT_APP_VIDEO_LINK
ARG REACT_APP_TUTORIAL_ONE
ARG REACT_APP_TUTORIAL_TWO
ARG REACT_APP_TUTORIAL_VIDEO
ARG REACT_APP_API_URL

ENV REACT_APP_MAPBOX_TOKEN=$REACT_APP_MAPBOX_TOKEN
ENV REACT_APP_MAPBOX_DATASETS_TOKEN=$REACT_APP_MAPBOX_DATASETS_TOKEN
ENV REACT_APP_GOOGLE_MAP_API_KEY=$REACT_APP_GOOGLE_MAP_API_KEY
ENV REACT_APP_GOOGLE_GEOCODE_API_KEY=$REACT_APP_GOOGLE_GEOCODE_API_KEY
ENV REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY
ENV REACT_APP_FIREBASE_AUTH=$REACT_APP_FIREBASE_AUTH
ENV REACT_APP_FIREBASE_PROJECT=$REACT_APP_FIREBASE_PROJECT
ENV REACT_APP_FIREBASE_BUCKET=$REACT_APP_FIREBASE_BUCKET
ENV REACT_APP_FIREBASE_MESS=$REACT_APP_FIREBASE_MESS
ENV REACT_APP_FIREBASE_APP_ID=$REACT_APP_FIREBASE_APP_ID
ENV REACT_APP_VIDEO_LINK=$REACT_APP_VIDEO_LINK
ENV REACT_APP_TUTORIAL_ONE=$REACT_APP_TUTORIAL_ONE
ENV REACT_APP_TUTORIAL_TWO=$REACT_APP_TUTORIAL_TWO
ENV REACT_APP_TUTORIAL_VIDEO=$REACT_APP_TUTORIAL_VIDEO
ENV REACT_APP_API_URL=$REACT_APP_API_URL

RUN npm run build --prefix ./app


# 2. Build backend
FROM node:16 AS backend

WORKDIR /server

COPY package*.json ./
RUN npm ci

COPY . ./
RUN npm run server-build


# 3. Final image
FROM node:16-slim

WORKDIR /app

# Copy backend code
COPY --from=backend /server /app

# Copy frontend build
COPY --from=frontend /app/build /app/build

# Set runtime ENV vars (for server only)
ENV NODE_ENV=production
ENV PORT=8080

EXPOSE 8080

CMD ["npm", "start"]
