import { AllUserScores } from "../../apis/user";
/*
export const fakeUserData: AllUserScores[] = [
  {
    username: "Uta Neal",
    create: 21,
    review: 20,
    labels: 14,
    modify: 31,
    email: "felis@outlook.edu",
    score: 23,
  },
  {
    username: "Beau Slater",
    create: 19,
    review: 10,
    labels: 29,
    modify: 26,
    email: "laoreet@yahoo.edu",
    score: 14,
  },
  {
    username: "Wendy Sargent",
    create: 34,
    review: 19,
    labels: 11,
    modify: 25,
    email: "natoque.penatibus.et@outlook.couk",
    score: 42,
  },
  {
    username: "Daphne Tyler",
    create: 5,
    review: 38,
    labels: 22,
    modify: 21,
    email: "commodo.tincidunt@yahoo.net",
    score: 39,
  },
  {
    username: "Galvin Horn",
    create: 49,
    review: 47,
    labels: 19,
    modify: 1,
    email: "eros.nec@icloud.ca",
    score: 31,
  },
  {
    username: "Coby Larsen",
    create: 45,
    review: 29,
    labels: 20,
    modify: 35,
    email: "integer@hotmail.org",
    score: 46,
  },
  {
    username: "Abel Colon",
    create: 3,
    review: 26,
    labels: 26,
    modify: 23,
    email: "massa@protonmail.com",
    score: 11,
  },
  {
    username: "Chantale Garrett",
    create: 20,
    review: 23,
    labels: 35,
    modify: 48,
    email: "nec@google.com",
    score: 11,
  },
  {
    username: "Ezekiel Estes",
    create: 31,
    review: 21,
    labels: 31,
    modify: 26,
    email: "euismod.et@yahoo.org",
    score: 6,
  },
  {
    username: "Patricia Manning",
    create: 3,
    review: 8,
    labels: 38,
    modify: 33,
    email: "faucibus.id.libero@google.net",
    score: 10,
  },
  {
    username: "Heather Briggs",
    create: 14,
    review: 24,
    labels: 3,
    modify: 36,
    email: "sapien.imperdiet@hotmail.ca",
    score: 18,
  },
  {
    username: "Selma Ewing",
    create: 1,
    review: 15,
    labels: 41,
    modify: 29,
    email: "vivamus@protonmail.ca",
    score: 38,
  },
  {
    username: "Kirk Wagner",
    create: 27,
    review: 42,
    labels: 22,
    modify: 10,
    email: "et@yahoo.org",
    score: 7,
  },
  {
    username: "Flavia Wong",
    create: 3,
    review: 45,
    labels: 26,
    modify: 46,
    email: "amet.massa@yahoo.edu",
    score: 42,
  },
  {
    username: "Brent Hale",
    create: 6,
    review: 47,
    labels: 37,
    modify: 20,
    email: "sed@hotmail.ca",
    score: 50,
  },
]; */
